INSERT INTO t_opex_forecast
    (
      PLANT_CODE,
      UNIT_CODE,
      FISCAL_YEAR,
      OPERATION_COST,
      MAINTENANCE_COST,
      CREATED_DATETIME,
      UPDATED_DATETIME,
      CREATE_BY,
      UPDATE_BY
    )
    VALUES
    :values
    ON DUPLICATE KEY UPDATE
      OPERATION_COST = VALUES(OPERATION_COST),
      MAINTENANCE_COST = VALUES(MAINTENANCE_COST),
      UPDATED_DATETIME = VALUES(UPDATED_DATETIME),
      UPDATE_BY = VALUES(UPDATE_BY)