INSERT INTO
  t_thermal_efficiency_forecast
(PLANT_CODE, UNIT_CODE, FISCAL_YEAR, CORRECTION_VALUE, CREATE_BY, UPDATE_BY) 
VALUES
:values
  ON DUPLICATE KEY UPDATE CORRECTION_VALUE = VALUES(CORRECTION_VALUE), UPDATE_BY = VALUES(UPDATE_BY)