INSERT INTO t_generation_output_forecast
    (
      PLANT_CODE,
      UNIT_CODE,
      FISCAL_YEAR,
      VALUE,
      CORRECTION_VALUE,
      CREATED_DATETIME,
      UPDATED_DATETIME,
      CREATE_BY,
      UPDATE_BY
    )
    VALUES
    :values
    ON DUPLICATE KEY UPDATE
      VALUE = VALUES(VALUE),
      CORRECTION_VALUE = VALUES(CORRECTION_VALUE),
      UPDATED_DATETIME = VALUES(UPDATED_DATETIME),
      UPDATE_BY = VALUES(UPDATE_BY)