INSERT INTO
    t_fuel_price_forecast (
        PLANT_CODE,
        FISCAL_YEAR,
        VALUE,
        CREATE_BY,
        UPDATE_BY
    )
VALUES
    (
        'HE_',
        :fiscalYear1,
        100,
        'test@mail.com',
        'test@mail.com'
    ),
    (
        'HE_',
        :fiscalYear2,
        121,
        'test@mail.com',
        'test@mail.com'
    ),
    (
        'HE_',
        :fiscalYear3,
        7552,
        'test@mail.com',
        'test@mail.com'
    ),
    (
        'HE_',
        :fiscalYear4,
        87,
        'test@mail.com',
        'test@mail.com'
    ),
    (
        'HE_',
        :fiscalYear5,
        0,
        'test@mail.com',
        'test@mail.com'
    ),
    (
        'HE_',
        :fiscalYear6,
        365.78,
        'test@mail.com',
        'test@mail.com'
    ),
    (
        'HE_',
        :fiscalYear7,
        781,
        'test@mail.com',
        'test@mail.com'
    ),
    (
        'HE_',
        :fiscalYear8,
        945,
        'test@mail.com',
        'test@mail.com'
    ),
    (
        'HE_',
        :fiscalYear9,
        NULL,
        'test@mail.com',
        'test@mail.com'
    ),
    (
        'HE_',
        :fiscalYear10,
        233,
        'test@mail.com',
        'test@mail.com'
    );