INSERT INTO m_asset
(PLANT_ID, ASSET_ID, ASSET_NAME, ASSET_CATEGORY, ASSET_TYPE, ASSET_STATUS, ASSET_CODE, manufacturer, model, PARENT_ASSET_CODE, PARENT_ASSET_ID, ASSET_KEY_FLAG)
VALUES
('HE_', 1, 'Asset Name', 'Walk-Around-Check', 'TYPE01', 'Green', 'HE_A100 CBM510 PG008', '', '', 'HE_A100 CBM510', 22629, 1);
