INSERT INTO
    t_fuel_price_plan (
        PLANT_CODE,
        FISCAL_YEAR,
        VALUE,
        CREATE_BY,
        UPDATE_BY
    )
VALUES
    (
        'HE_',
        2018,
        100,
        'test@mail.com',
        'test@mail.com'
    ),
    (
        'HE_',
        2019,
        121,
        'test@mail.com',
        'test@mail.com'
    ),
    (
        'HE_',
        2021,
        100,
        'test@mail.com',
        'test@mail.com'
    ),
    (
        'HE_',
        2022,
        121,
        'test@mail.com',
        'test@mail.com'
    ),
    (
        'HE_',
        2023,
        7552,
        'test@mail.com',
        'test@mail.com'
    ),
    (
        'HE_',
        2024,
        87,
        'test@mail.com',
        'test@mail.com'
    ),
    (
        'HE_',
        2025,
        0,
        'test@mail.com',
        'test@mail.com'
    ),
    (
        'HE_',
        2026,
        365.78,
        'test@mail.com',
        'test@mail.com'
    ),
    (
        'HE_',
        2027,
        781,
        'test@mail.com',
        'test@mail.com'
    ),
    (
        'HE_',
        2028,
        945,
        'test@mail.com',
        'test@mail.com'
    ),
    (
        'HE_',
        2029,
        NULL,
        'test@mail.com',
        'test@mail.com'
    ),
    (
        'HE_',
        2099,
        233,
        'test@mail.com',
        'test@mail.com'
    );