INSERT INTO
    t_basic_charge_forecast (
        PLANT_CODE,
        UNIT_CODE,
        FISCAL_YEAR,
        OPERATION_INPUT,
        MAINTENANCE_INPUT,
        CREATE_BY,
        UPDATE_BY
    )
VALUES
    (
        'HK_',
        'HK_A100',
        2021,
        NULL,
        85.21,
        'test@mail.com',
        'test@mail.com'
    ),
    (
        'HE_',
        'HE_A100',
        2021,
        121.45,
        0.00,
        'test@mail.com',
        'test@mail.com'
    ),
    (
        'HE_',
        'HE_A200',
        2021,
        578.45,
        75.52,
        'test@mail.com',
        'test@mail.com'
    ),
    (
        'HE_',
        'HE_A300',
        2021,
        87.47,
        15.84,
        'test@mail.com',
        'test@mail.com'
    ),
    (
        'HE_',
        'HE_A100',
        2022,
        98.78,
        94.51,
        'test@mail.com',
        'test@mail.com'
    ),
    (
        'HE_',
        'HE_A200',
        2022,
        365.78,
        34.51,
        'test@mail.com',
        'test@mail.com'
    ),
    (
        'HE_',
        'HE_A300',
        2022,
        78.21,
        94.62,
        'test@mail.com',
        'test@mail.com'
    ),
    (
        'HE_',
        'HE_A100',
        2023,
        987.45,
        75.15,
        'test@mail.com',
        'test@mail.com'
    ),
    (
        'HE_',
        'HE_A200',
        2023,
        NULL,
        NULL,
        'test@mail.com',
        'test@mail.com'
    ),
    (
        'HE_',
        'HE_A300',
        2023,
        0.00,
        94.62,
        'test@mail.com',
        'test@mail.com'
    ),
    (
        'HE_',
        'HE_A100',
        2024,
        98.64,
        78.62,
        'test@mail.com',
        'test@mail.com'
    ),
    (
        'HE_',
        'HE_A200',
        2024,
        654.74,
        71.52,
        'test@mail.com',
        'test@mail.com'
    ),
    (
        'HE_',
        'HE_A300',
        2024,
        325.8,
        98.2,
        'test@mail.com',
        'test@mail.com'
    ),
    (
        'HE_',
        'HE_A100',
        2025,
        98.64,
        78.62,
        'test@mail.com',
        'test@mail.com'
    ),
    (
        'HE_',
        'HE_A200',
        2025,
        654.74,
        71.52,
        'test@mail.com',
        'test@mail.com'
    ),
    (
        'HE_',
        'HE_A300',
        2025,
        325.8,
        98.2,
        'test@mail.com',
        'test@mail.com'
    ),
    (
        'HE_',
        'HE_A100',
        2026,
        98.64,
        78.62,
        'test@mail.com',
        'test@mail.com'
    ),
    (
        'HE_',
        'HE_A200',
        2026,
        654.74,
        71.52,
        'test@mail.com',
        'test@mail.com'
    ),
    (
        'HE_',
        'HE_A300',
        2026,
        325.8,
        98.2,
        'test@mail.com',
        'test@mail.com'
    );